name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
      feature_flag:
        description: "Enable feature flag"
        required: false
        default: "false"

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "This workflow has been triggered manually"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "FF: ${{ github.event.inputs.feature_flag }}"
